spring.application.name=web

server.servlet.context-path=/poezd/

spring.datasource.url=jdbc:postgresql://localhost:5432/poezd
spring.datasource.username=poezd
spring.datasource.password=BigPoezd52Ura
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true



